# 爬虫工具的配置文件

# 爬虫抓取的版本
# 目前只有 1.7.10, 1.8.9, 1.9.4, 1.10.2, 1.11.2, 1.12.2 四个可选
version: 1.12.2

# 爬虫的线程数
threads_num: 20

# 爬虫的爬取的 mod 页数
mod_page: 20

# 爬虫爬取的 modpack 页数
# 这一处是专门下载 FTB 整合的，curse 上整合低端的太多，就用白名单了
modpack_page: 1

# 爬虫爬取 mod 的白名单，在此名单上的 mod 会被爬取
# 名单请使用 curseforge url 中的名称
mod_whitelist:
  - integrated-rest # 经典的集成动力学模组附属，支持网络通信
  - automated-redstone
  - inspirations
  - teletoro
  - simulated-nights
  - mrcrayfishs-device-mod # 家具模组作者的作品
  - mrcrayfishs-jumping-castle-mod # 家具模组作者的作品
  - dab-mod # 家具模组作者的作品
  - angry-pixel-the-betweenlands-mod # 交错维度
  - taiga-tinkers-alloying-addon # 一个添加了很多合金的匠魂附属
  - techguns # 大名鼎鼎的科技枪
  - immersive-railroading # 沉浸铁路！太棒！
  - technomancy-2 # Noct943要求添加的模组
  - practical-logistics-2 # 实用物流拓展
  - bionisation-3 # Noct943要求添加的模组
  - rockhounding-mod-surface
  - rockhounding-mod-rocks
  - rockhounding-mod-core
  - rockhounding-mod-ore-tiers
  - rockhounding-mod-chemistry
  - autoverse # wz 钦点
  - hungryanimals
  - hungry-mechanics
  - gregtechce # 格雷科技社区版，重写的语言文件就是方便

# 爬虫爬取 modpack 白名单，在此名单上的 modpack 会被爬取
# 仅适用于 curseforge 整合
# 名单请使用 curseforge url 中的名称
modpack_whitelist:
  - all-the-mods-3
  - modern-skyblock-2
  - modern-skyblock-3-departed
  - minecolonies-testpack
  - forever-stranded-lost-souls
  - nfinit-skyblock
  - sevtech-ages
  - exoria

# 爬虫爬取 mod 的白名单，在此名单上的模组和整合包会被禁止爬取，会覆盖白名单
# 名单请使用 curseforge url 中的名称
mod_blacklist:
  - dungeon-tactics # 乱码
  - minecraft-comes-alive-mca # 无意义人名翻译
  - bookshelf # 无意义附魔等级翻译
  - mike-dongles # 无意义粉丝向模组
  - magical-psi # 仅仅改材质，但是作者忘记删语言文件了
  - the-twilight-forest # 目前有他人对此翻译存在反对观点，暂时列为黑名单，规避冲突
  - charset-lib # 3TUSK 指出不需要翻译
  - metamorph # horsewithnoname 的模组
  - aperture # horsewithnoname 的模组
  - blockbuster # horsewithnoname 的模组
  - imaginary # horsewithnoname 的模组
  - greenscreen
  - slashblade # 翻译问题较多，目前上传了固定版本，不再变动
  - the-aether-ii
  - extraplanets # 岩浆水覆盖问题
  - shetiphiancore # 染料颜色重名问题

# 爬虫爬取 modpack 黑名单，在此名单上的模组和整合包会被禁止爬取，会覆盖白名单
# 名单请使用 curseforge url 中的名称
modpack_blacklist:
  - the-new-frontier # 这个整合会莫名其妙不存在文件

# del list 名单，用于清除不需要提交的 assets 文件
# 需要写入对应的 assets 文件名，不是 url 名称
del_list:
  - writing_guides
  - chisel_guide # 凿子 mod 的手册，无需翻译
  - pokecube_books # pokecube 模组手册，乱码无法翻译
  - bloodmagicguide # 血魔法手册，无需翻译
  - evilcraftcompat # 附带在 EvilCraft 内的兼容性 mod，无语言文件
  - torohealthmod # ToroHealth Damage Indicators 血量显示 mod，无语言文件
  - packmode # 无语言文件
  - shulkerbox # Advanced Shulkerboxes，一个可以在背包直接打开潜影盒的 mod，无语言文件
  - progressivebosses # 错误编码
  - jaopca # 会导致崩溃
  - tinkersdefense # 新版本已经修改名称，这个名称属于旧版本残留，删去

# 邮件发送提醒
# 按次序写入需要发送的邮箱
email:
  - baka943@qq.com

# github 仓库信息获取
# 已经获得下面所有人的授权，允许抓取公开信息
# 遵循 github 用户协议
# github_user:
# - 3TUSK
# - J-swl
# - DYColdWind
# - SihenZhang
# - forestbat
