name: CheckMerge

on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check_availability:
    runs-on: windows-latest
    steps:
      - name: Check Label
        uses: jesusvasquez333/verify-pr-label-action@v1.3.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "needmerge"
          pull-request-number: "${{ github.event.pull_request.number }}"
