name: Processor-ce

on: 
  push:
      #branches: [ 1.12.2 ]
      #paths-ignore: '**/*nfo.json'
  schedule:
    - cron: '0 1 3,17 * *'

    

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build processor
        run: dotnet publish .\src\Processor\Processor.csproj -o ./ -r win-x64 -p:PublishSingleFile=true

      - name: Run processor
        run: .\Processor --Ce

      - name: Push  to github repo
        if: ${{github.event}} == 'push'
        run: |
          ri .\Processor.exe -Force
          $ErrorActionPreference ='Continue'
          git config --global credential.helper manager
          git config --global user.email "fanng233@gmail.com"
          git config --global user.name "baka-gourd"
          @"
          protocol=https
          host=github.com
          username=baka-gourd
          password=${{secrets.BAKA_GOURD_TOKEN}}
          "@ > .\1.txt
          gc 1.txt|git credential-manager  store
          ri .\1.txt -Force
          git add .
          git commit -m "创建空文件"
          git push origin HEAD:${{ github.ref }}