name: Spider

on: 
  push:
    paths-ignore: '**/*nfo.json'
    

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      # - name: Setup .NET Core SDK
      #   uses: actions/setup-dotnet@v1.5.0
      #   with:
      #     dotnet-version: 3.1.401
      
      # - name: Setup BuildXL
      #   uses: summpot/setup-bxl@v1.0.0

      # - name: Setup Java JDK
      #   uses: actions/setup-java@v1.4.1
      #   with:
      #     java-version: 1.8
      #     java-package: jre

      - name: Build spider
        run: dotnet publish .\src\Spider\Spider.csproj -o ./ -r win-x64 -p:PublishSingleFile=true

      - name: Run spider
        run: .\Spider

      - name: Push  to github
        if: ${{github.event}} == 'push'
        run: |
          ri .\Spider.exe -Force
          $ErrorActionPreference ='Continue'
          git config --global credential.helper manager
          git config --global user.email "bot@cfpa.com"
          git config --global user.name "CfpaBot"
          @"
          protocol=https
          host=github.com
          username=summpot
          password=${{secrets.SUMMPOT_TOKEN}}
          "@ > .\1.txt
          gc 1.txt|git credential-manager  store
          ri .\1.txt -Force
          git add .
          git commit -m "Update mod_info.json"
          git push origin HEAD:${{ github.ref }}
